### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by MMDasa** [advaita-krishna-das/gem#106]
По аналогии с Comment ("Your comment is submitted"), при подаче голоса уведомлять голосовавшего о том, что он проголосовал  определенным образом:

"Your vote in favor has been submitted"
"Your vote against has been submitted"
"Your abstention has been submitted"

Если он меняет голос, то должен получить уведомление: 

"Your [vote in favor/vote agains/abstention] has been changed to  [vote in favor/vote agains/abstention]"

По истечении времени голосования должно быть извещение "Voting is over" и кнопки должны деактивироваться.

**Comment by advaita-krishna-das** [comment]
Done
