### ISSUE TITLE
Information line in all views

### ISSUE THREAD

**Issue by MMDasa** [advaita-krishna-das/gem#86]
Добавить информационную строку на все экраны приложения, содержащую сводную и обновляющуюся в реальном времени информацию о подключенных к системе на текущий момент участниках, например:

GBC members: 25 | Ministers: 6 | Deputies: 12 | Guests: 3 | Total: 46 

а также название сессии и время, оставшееся до ее окончания.

**Comment by advaita-krishna-das** [comment]
![image](https://user-images.githubusercontent.com/22368151/34774565-d9bcbe14-f620-11e7-8440-abd126875526.png)

**Comment by advaita-krishna-das** [comment]
Для секретаря:
![image](https://user-images.githubusercontent.com/22368151/34774599-fbfadee8-f620-11e7-9011-d554bf7cdd60.png)

**Comment by advaita-krishna-das** [comment]
Done
