### ISSUE TITLE
Quorum: setting, displaying, checking

### ISSUE THREAD

**Issue by MMDasa** [advaita-krishna-das/gem#87]
Предусмотреть задание кворума (числа присутствующих членов Джибиси с правом голоса, минимально необходимого для принятия решений). На данный момент кворум равен 19.

Предусмотреть возможность его изменения, чтобы для этого требовалось одновременное участие секретаря и трое членов Исполнительного комитета – например, чтобы все четверо были залогинены и получили по две цифры от случайного восьмизначного кода, который должен ввести целиком секретарь для изменения кворума.

GEM должен позволять ставить вопросы на окончательное голосование только при наличии числа участников, большего или равного кворуму.

**Comment by advaita-krishna-das** [comment]
Что делать, если число членов Исполнительного комитета меньше/больше трёх?
Должно ли где-то настраиваться минимальное количество?

Сейчас работает так:
Если число членов Исполнительного комитета больше трёх, то выбираются троих случайным образом.
Если меньше, то работаем с теми кто есть.
Если никого нет, GEM позволяет задать quorum без кода.

**Comment by MMDasa** [comment]
Число членов Исполкома – всегда три человека: председатель Джибиси и две заместителя.

**Comment by advaita-krishna-das** [comment]
Done
